/* jswriter.c generated by valac 0.16.1, the Vala compiler
 * generated from jswriter.vala, do not modify */

/* jswriter.vala
 *
 * Copyright (C) 2010  Luca Bruno
 * Copyright (C) 2006-2009  Jürg Billeter
 *
 * This file is part of Maja, derived from valacodewriter.vala of Vala.
 *
 * Maja is free software; you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation; either version 3 of
 * the License, or (at your option) any later version.
 *
 * Maja is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with Maja. If not, see <http://www.gnu.org/licenses/>.
 *
 * Author:
 * 	Luca Bruno <lethalman88@gmail.com>
 */

#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include <glib/gstdio.h>
#include <gobject/gvaluecollector.h>


#define MAJA_TYPE_JS_WRITER (maja_js_writer_get_type ())
#define MAJA_JS_WRITER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MAJA_TYPE_JS_WRITER, MajaJSWriter))
#define MAJA_JS_WRITER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), MAJA_TYPE_JS_WRITER, MajaJSWriterClass))
#define MAJA_IS_JS_WRITER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MAJA_TYPE_JS_WRITER))
#define MAJA_IS_JS_WRITER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), MAJA_TYPE_JS_WRITER))
#define MAJA_JS_WRITER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), MAJA_TYPE_JS_WRITER, MajaJSWriterClass))

typedef struct _MajaJSWriter MajaJSWriter;
typedef struct _MajaJSWriterClass MajaJSWriterClass;
typedef struct _MajaJSWriterPrivate MajaJSWriterPrivate;
#define _g_free0(var) (var = (g_free (var), NULL))
#define _fclose0(var) ((var == NULL) ? NULL : (var = (fclose (var), NULL)))
#define _g_mapped_file_free0(var) ((var == NULL) ? NULL : (var = (g_mapped_file_free (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
#define _g_regex_unref0(var) ((var == NULL) ? NULL : (var = (g_regex_unref (var), NULL)))
typedef struct _MajaParamSpecJSWriter MajaParamSpecJSWriter;

struct _MajaJSWriter {
	GTypeInstance parent_instance;
	volatile int ref_count;
	MajaJSWriterPrivate * priv;
};

struct _MajaJSWriterClass {
	GTypeClass parent_class;
	void (*finalize) (MajaJSWriter *self);
};

struct _MajaJSWriterPrivate {
	gchar* _filename;
	gchar* source_filename;
	gchar* temp_filename;
	gboolean file_exists;
	FILE* stream;
	gint indent;
	gboolean _bol;
};

struct _MajaParamSpecJSWriter {
	GParamSpec parent_instance;
};


static gpointer maja_js_writer_parent_class = NULL;

gpointer maja_js_writer_ref (gpointer instance);
void maja_js_writer_unref (gpointer instance);
GParamSpec* maja_param_spec_js_writer (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void maja_value_set_js_writer (GValue* value, gpointer v_object);
void maja_value_take_js_writer (GValue* value, gpointer v_object);
gpointer maja_value_get_js_writer (const GValue* value);
GType maja_js_writer_get_type (void) G_GNUC_CONST;
#define MAJA_JS_WRITER_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), MAJA_TYPE_JS_WRITER, MajaJSWriterPrivate))
enum  {
	MAJA_JS_WRITER_DUMMY_PROPERTY
};
MajaJSWriter* maja_js_writer_new (const gchar* filename, const gchar* source_filename);
MajaJSWriter* maja_js_writer_construct (GType object_type, const gchar* filename, const gchar* source_filename);
void maja_js_writer_set_filename (MajaJSWriter* self, const gchar* value);
gboolean maja_js_writer_open (MajaJSWriter* self, gboolean write_version);
const gchar* maja_js_writer_get_filename (MajaJSWriter* self);
void maja_js_writer_write_string (MajaJSWriter* self, const gchar* s);
void maja_js_writer_write_newline (MajaJSWriter* self);
void maja_js_writer_close (MajaJSWriter* self);
void maja_js_writer_write_indent (MajaJSWriter* self);
gboolean maja_js_writer_get_bol (MajaJSWriter* self);
void maja_js_writer_write_begin_block (MajaJSWriter* self);
void maja_js_writer_write_end_block (MajaJSWriter* self);
void maja_js_writer_write_comment (MajaJSWriter* self, const gchar* text);
static void maja_js_writer_finalize (MajaJSWriter* obj);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);
static gint _vala_array_length (gpointer array);


MajaJSWriter* maja_js_writer_construct (GType object_type, const gchar* filename, const gchar* source_filename) {
	MajaJSWriter* self = NULL;
	const gchar* _tmp0_;
	const gchar* _tmp1_;
	gchar* _tmp2_;
#line 58 "/home/digi/Documents/MajaC/majac/jswriter.vala"
	g_return_val_if_fail (filename != NULL, NULL);
#line 58 "/home/digi/Documents/MajaC/majac/jswriter.vala"
	self = (MajaJSWriter*) g_type_create_instance (object_type);
#line 59 "/home/digi/Documents/MajaC/majac/jswriter.vala"
	_tmp0_ = filename;
#line 59 "/home/digi/Documents/MajaC/majac/jswriter.vala"
	maja_js_writer_set_filename (self, _tmp0_);
#line 60 "/home/digi/Documents/MajaC/majac/jswriter.vala"
	_tmp1_ = source_filename;
#line 60 "/home/digi/Documents/MajaC/majac/jswriter.vala"
	_tmp2_ = g_strdup (_tmp1_);
#line 60 "/home/digi/Documents/MajaC/majac/jswriter.vala"
	_g_free0 (self->priv->source_filename);
#line 60 "/home/digi/Documents/MajaC/majac/jswriter.vala"
	self->priv->source_filename = _tmp2_;
#line 58 "/home/digi/Documents/MajaC/majac/jswriter.vala"
	return self;
#line 136 "jswriter.c"
}


MajaJSWriter* maja_js_writer_new (const gchar* filename, const gchar* source_filename) {
#line 58 "/home/digi/Documents/MajaC/majac/jswriter.vala"
	return maja_js_writer_construct (MAJA_TYPE_JS_WRITER, filename, source_filename);
#line 143 "jswriter.c"
}


/**
 * Opens the file.
 *
 * @return true if the file has been opened successfully,
 *         false otherwise
 */
gboolean maja_js_writer_open (MajaJSWriter* self, gboolean write_version) {
	gboolean result = FALSE;
	const gchar* _tmp0_;
	gboolean _tmp1_ = FALSE;
	gboolean _tmp2_;
	FILE* _tmp12_;
	const gchar* _tmp13_;
	gchar* _tmp14_ = NULL;
	gchar* _tmp15_;
	gchar* _tmp16_ = NULL;
	gchar* _tmp17_;
	gchar* opening;
	const gchar* _tmp18_;
	const gchar* _tmp19_;
#line 69 "/home/digi/Documents/MajaC/majac/jswriter.vala"
	g_return_val_if_fail (self != NULL, FALSE);
#line 70 "/home/digi/Documents/MajaC/majac/jswriter.vala"
	_tmp0_ = self->priv->_filename;
#line 70 "/home/digi/Documents/MajaC/majac/jswriter.vala"
	_tmp1_ = g_file_test (_tmp0_, G_FILE_TEST_EXISTS);
#line 70 "/home/digi/Documents/MajaC/majac/jswriter.vala"
	self->priv->file_exists = _tmp1_;
#line 71 "/home/digi/Documents/MajaC/majac/jswriter.vala"
	_tmp2_ = self->priv->file_exists;
#line 71 "/home/digi/Documents/MajaC/majac/jswriter.vala"
	if (_tmp2_) {
#line 179 "jswriter.c"
		const gchar* _tmp3_;
		gchar* _tmp4_ = NULL;
		const gchar* _tmp5_;
		FILE* _tmp6_ = NULL;
#line 72 "/home/digi/Documents/MajaC/majac/jswriter.vala"
		_tmp3_ = self->priv->_filename;
#line 72 "/home/digi/Documents/MajaC/majac/jswriter.vala"
		_tmp4_ = g_strdup_printf ("%s.valatmp", _tmp3_);
#line 72 "/home/digi/Documents/MajaC/majac/jswriter.vala"
		_g_free0 (self->priv->temp_filename);
#line 72 "/home/digi/Documents/MajaC/majac/jswriter.vala"
		self->priv->temp_filename = _tmp4_;
#line 73 "/home/digi/Documents/MajaC/majac/jswriter.vala"
		_tmp5_ = self->priv->temp_filename;
#line 73 "/home/digi/Documents/MajaC/majac/jswriter.vala"
		_tmp6_ = fopen (_tmp5_, "w");
#line 73 "/home/digi/Documents/MajaC/majac/jswriter.vala"
		_fclose0 (self->priv->stream);
#line 73 "/home/digi/Documents/MajaC/majac/jswriter.vala"
		self->priv->stream = _tmp6_;
#line 200 "jswriter.c"
	} else {
		const gchar* _tmp7_;
		gchar* _tmp8_ = NULL;
		gchar* dirname;
		const gchar* _tmp9_;
		const gchar* _tmp10_;
		FILE* _tmp11_ = NULL;
#line 79 "/home/digi/Documents/MajaC/majac/jswriter.vala"
		_tmp7_ = self->priv->_filename;
#line 79 "/home/digi/Documents/MajaC/majac/jswriter.vala"
		_tmp8_ = g_path_get_dirname (_tmp7_);
#line 79 "/home/digi/Documents/MajaC/majac/jswriter.vala"
		dirname = _tmp8_;
#line 80 "/home/digi/Documents/MajaC/majac/jswriter.vala"
		_tmp9_ = dirname;
#line 80 "/home/digi/Documents/MajaC/majac/jswriter.vala"
		g_mkdir_with_parents (_tmp9_, 0755);
#line 81 "/home/digi/Documents/MajaC/majac/jswriter.vala"
		_tmp10_ = self->priv->_filename;
#line 81 "/home/digi/Documents/MajaC/majac/jswriter.vala"
		_tmp11_ = fopen (_tmp10_, "w");
#line 81 "/home/digi/Documents/MajaC/majac/jswriter.vala"
		_fclose0 (self->priv->stream);
#line 81 "/home/digi/Documents/MajaC/majac/jswriter.vala"
		self->priv->stream = _tmp11_;
#line 71 "/home/digi/Documents/MajaC/majac/jswriter.vala"
		_g_free0 (dirname);
#line 228 "jswriter.c"
	}
#line 84 "/home/digi/Documents/MajaC/majac/jswriter.vala"
	_tmp12_ = self->priv->stream;
#line 84 "/home/digi/Documents/MajaC/majac/jswriter.vala"
	if (_tmp12_ == NULL) {
#line 85 "/home/digi/Documents/MajaC/majac/jswriter.vala"
		result = FALSE;
#line 85 "/home/digi/Documents/MajaC/majac/jswriter.vala"
		return result;
#line 238 "jswriter.c"
	}
#line 88 "/home/digi/Documents/MajaC/majac/jswriter.vala"
	_tmp13_ = self->priv->_filename;
#line 88 "/home/digi/Documents/MajaC/majac/jswriter.vala"
	_tmp14_ = g_path_get_basename (_tmp13_);
#line 88 "/home/digi/Documents/MajaC/majac/jswriter.vala"
	_tmp15_ = _tmp14_;
#line 88 "/home/digi/Documents/MajaC/majac/jswriter.vala"
	_tmp16_ = g_strdup_printf ("/* %s generated by majac, the Maja compiler", _tmp15_);
#line 88 "/home/digi/Documents/MajaC/majac/jswriter.vala"
	_tmp17_ = _tmp16_;
#line 88 "/home/digi/Documents/MajaC/majac/jswriter.vala"
	_g_free0 (_tmp15_);
#line 88 "/home/digi/Documents/MajaC/majac/jswriter.vala"
	opening = _tmp17_;
#line 89 "/home/digi/Documents/MajaC/majac/jswriter.vala"
	_tmp18_ = opening;
#line 89 "/home/digi/Documents/MajaC/majac/jswriter.vala"
	maja_js_writer_write_string (self, _tmp18_);
#line 92 "/home/digi/Documents/MajaC/majac/jswriter.vala"
	_tmp19_ = self->priv->source_filename;
#line 92 "/home/digi/Documents/MajaC/majac/jswriter.vala"
	if (_tmp19_ != NULL) {
#line 262 "jswriter.c"
		const gchar* _tmp20_;
		gchar* _tmp21_ = NULL;
		gchar* _tmp22_;
		gchar* _tmp23_ = NULL;
		gchar* _tmp24_;
#line 93 "/home/digi/Documents/MajaC/majac/jswriter.vala"
		maja_js_writer_write_newline (self);
#line 94 "/home/digi/Documents/MajaC/majac/jswriter.vala"
		_tmp20_ = self->priv->source_filename;
#line 94 "/home/digi/Documents/MajaC/majac/jswriter.vala"
		_tmp21_ = g_path_get_basename (_tmp20_);
#line 94 "/home/digi/Documents/MajaC/majac/jswriter.vala"
		_tmp22_ = _tmp21_;
#line 94 "/home/digi/Documents/MajaC/majac/jswriter.vala"
		_tmp23_ = g_strdup_printf (" * generated from %s", _tmp22_);
#line 94 "/home/digi/Documents/MajaC/majac/jswriter.vala"
		_tmp24_ = _tmp23_;
#line 94 "/home/digi/Documents/MajaC/majac/jswriter.vala"
		maja_js_writer_write_string (self, _tmp24_);
#line 94 "/home/digi/Documents/MajaC/majac/jswriter.vala"
		_g_free0 (_tmp24_);
#line 94 "/home/digi/Documents/MajaC/majac/jswriter.vala"
		_g_free0 (_tmp22_);
#line 286 "jswriter.c"
	}
#line 97 "/home/digi/Documents/MajaC/majac/jswriter.vala"
	maja_js_writer_write_string (self, ", do not modify */");
#line 98 "/home/digi/Documents/MajaC/majac/jswriter.vala"
	maja_js_writer_write_newline (self);
#line 99 "/home/digi/Documents/MajaC/majac/jswriter.vala"
	maja_js_writer_write_newline (self);
#line 101 "/home/digi/Documents/MajaC/majac/jswriter.vala"
	result = TRUE;
#line 101 "/home/digi/Documents/MajaC/majac/jswriter.vala"
	_g_free0 (opening);
#line 101 "/home/digi/Documents/MajaC/majac/jswriter.vala"
	return result;
#line 300 "jswriter.c"
}


/**
 * Closes the file.
 */
void maja_js_writer_close (MajaJSWriter* self) {
	gboolean _tmp0_;
	GError * _inner_error_ = NULL;
#line 107 "/home/digi/Documents/MajaC/majac/jswriter.vala"
	g_return_if_fail (self != NULL);
#line 108 "/home/digi/Documents/MajaC/majac/jswriter.vala"
	_fclose0 (self->priv->stream);
#line 108 "/home/digi/Documents/MajaC/majac/jswriter.vala"
	self->priv->stream = NULL;
#line 110 "/home/digi/Documents/MajaC/majac/jswriter.vala"
	_tmp0_ = self->priv->file_exists;
#line 110 "/home/digi/Documents/MajaC/majac/jswriter.vala"
	if (_tmp0_) {
#line 320 "jswriter.c"
		gboolean changed;
		gboolean _tmp16_;
#line 111 "/home/digi/Documents/MajaC/majac/jswriter.vala"
		changed = TRUE;
#line 325 "jswriter.c"
		{
			const gchar* _tmp1_;
			GMappedFile* _tmp2_;
			GMappedFile* old_file;
			const gchar* _tmp3_;
			GMappedFile* _tmp4_;
			GMappedFile* new_file;
			GMappedFile* _tmp5_;
			gsize _tmp6_ = 0UL;
			gsize len;
			gsize _tmp7_;
			GMappedFile* _tmp8_;
			gsize _tmp9_ = 0UL;
#line 114 "/home/digi/Documents/MajaC/majac/jswriter.vala"
			_tmp1_ = self->priv->_filename;
#line 114 "/home/digi/Documents/MajaC/majac/jswriter.vala"
			_tmp2_ = g_mapped_file_new (_tmp1_, FALSE, &_inner_error_);
#line 114 "/home/digi/Documents/MajaC/majac/jswriter.vala"
			old_file = _tmp2_;
#line 114 "/home/digi/Documents/MajaC/majac/jswriter.vala"
			if (_inner_error_ != NULL) {
#line 114 "/home/digi/Documents/MajaC/majac/jswriter.vala"
				if (_inner_error_->domain == G_FILE_ERROR) {
#line 349 "jswriter.c"
					goto __catch2_g_file_error;
				}
#line 114 "/home/digi/Documents/MajaC/majac/jswriter.vala"
				g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 114 "/home/digi/Documents/MajaC/majac/jswriter.vala"
				g_clear_error (&_inner_error_);
#line 114 "/home/digi/Documents/MajaC/majac/jswriter.vala"
				return;
#line 358 "jswriter.c"
			}
#line 115 "/home/digi/Documents/MajaC/majac/jswriter.vala"
			_tmp3_ = self->priv->temp_filename;
#line 115 "/home/digi/Documents/MajaC/majac/jswriter.vala"
			_tmp4_ = g_mapped_file_new (_tmp3_, FALSE, &_inner_error_);
#line 115 "/home/digi/Documents/MajaC/majac/jswriter.vala"
			new_file = _tmp4_;
#line 115 "/home/digi/Documents/MajaC/majac/jswriter.vala"
			if (_inner_error_ != NULL) {
#line 115 "/home/digi/Documents/MajaC/majac/jswriter.vala"
				_g_mapped_file_free0 (old_file);
#line 115 "/home/digi/Documents/MajaC/majac/jswriter.vala"
				if (_inner_error_->domain == G_FILE_ERROR) {
#line 372 "jswriter.c"
					goto __catch2_g_file_error;
				}
#line 115 "/home/digi/Documents/MajaC/majac/jswriter.vala"
				_g_mapped_file_free0 (old_file);
#line 115 "/home/digi/Documents/MajaC/majac/jswriter.vala"
				g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 115 "/home/digi/Documents/MajaC/majac/jswriter.vala"
				g_clear_error (&_inner_error_);
#line 115 "/home/digi/Documents/MajaC/majac/jswriter.vala"
				return;
#line 383 "jswriter.c"
			}
#line 116 "/home/digi/Documents/MajaC/majac/jswriter.vala"
			_tmp5_ = old_file;
#line 116 "/home/digi/Documents/MajaC/majac/jswriter.vala"
			_tmp6_ = g_mapped_file_get_length (_tmp5_);
#line 116 "/home/digi/Documents/MajaC/majac/jswriter.vala"
			len = _tmp6_;
#line 117 "/home/digi/Documents/MajaC/majac/jswriter.vala"
			_tmp7_ = len;
#line 117 "/home/digi/Documents/MajaC/majac/jswriter.vala"
			_tmp8_ = new_file;
#line 117 "/home/digi/Documents/MajaC/majac/jswriter.vala"
			_tmp9_ = g_mapped_file_get_length (_tmp8_);
#line 117 "/home/digi/Documents/MajaC/majac/jswriter.vala"
			if (_tmp7_ == _tmp9_) {
#line 399 "jswriter.c"
				GMappedFile* _tmp10_;
				gchar* _tmp11_ = NULL;
				GMappedFile* _tmp12_;
				gchar* _tmp13_ = NULL;
				gsize _tmp14_;
				gint _tmp15_ = 0;
#line 118 "/home/digi/Documents/MajaC/majac/jswriter.vala"
				_tmp10_ = old_file;
#line 118 "/home/digi/Documents/MajaC/majac/jswriter.vala"
				_tmp11_ = g_mapped_file_get_contents (_tmp10_);
#line 118 "/home/digi/Documents/MajaC/majac/jswriter.vala"
				_tmp12_ = new_file;
#line 118 "/home/digi/Documents/MajaC/majac/jswriter.vala"
				_tmp13_ = g_mapped_file_get_contents (_tmp12_);
#line 118 "/home/digi/Documents/MajaC/majac/jswriter.vala"
				_tmp14_ = len;
#line 118 "/home/digi/Documents/MajaC/majac/jswriter.vala"
				_tmp15_ = memcmp (_tmp11_, _tmp13_, _tmp14_);
#line 118 "/home/digi/Documents/MajaC/majac/jswriter.vala"
				if (_tmp15_ == 0) {
#line 119 "/home/digi/Documents/MajaC/majac/jswriter.vala"
					changed = FALSE;
#line 422 "jswriter.c"
				}
			}
#line 122 "/home/digi/Documents/MajaC/majac/jswriter.vala"
			_g_mapped_file_free0 (old_file);
#line 122 "/home/digi/Documents/MajaC/majac/jswriter.vala"
			old_file = NULL;
#line 123 "/home/digi/Documents/MajaC/majac/jswriter.vala"
			_g_mapped_file_free0 (new_file);
#line 123 "/home/digi/Documents/MajaC/majac/jswriter.vala"
			new_file = NULL;
#line 113 "/home/digi/Documents/MajaC/majac/jswriter.vala"
			_g_mapped_file_free0 (new_file);
#line 113 "/home/digi/Documents/MajaC/majac/jswriter.vala"
			_g_mapped_file_free0 (old_file);
#line 437 "jswriter.c"
		}
		goto __finally2;
		__catch2_g_file_error:
		{
			GError* e = NULL;
#line 113 "/home/digi/Documents/MajaC/majac/jswriter.vala"
			e = _inner_error_;
#line 113 "/home/digi/Documents/MajaC/majac/jswriter.vala"
			_inner_error_ = NULL;
#line 113 "/home/digi/Documents/MajaC/majac/jswriter.vala"
			_g_error_free0 (e);
#line 449 "jswriter.c"
		}
		__finally2:
#line 113 "/home/digi/Documents/MajaC/majac/jswriter.vala"
		if (_inner_error_ != NULL) {
#line 113 "/home/digi/Documents/MajaC/majac/jswriter.vala"
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 113 "/home/digi/Documents/MajaC/majac/jswriter.vala"
			g_clear_error (&_inner_error_);
#line 113 "/home/digi/Documents/MajaC/majac/jswriter.vala"
			return;
#line 460 "jswriter.c"
		}
#line 128 "/home/digi/Documents/MajaC/majac/jswriter.vala"
		_tmp16_ = changed;
#line 128 "/home/digi/Documents/MajaC/majac/jswriter.vala"
		if (_tmp16_) {
#line 466 "jswriter.c"
			const gchar* _tmp17_;
			const gchar* _tmp18_;
#line 129 "/home/digi/Documents/MajaC/majac/jswriter.vala"
			_tmp17_ = self->priv->temp_filename;
#line 129 "/home/digi/Documents/MajaC/majac/jswriter.vala"
			_tmp18_ = self->priv->_filename;
#line 129 "/home/digi/Documents/MajaC/majac/jswriter.vala"
			g_rename (_tmp17_, _tmp18_);
#line 475 "jswriter.c"
		} else {
			const gchar* _tmp19_;
#line 131 "/home/digi/Documents/MajaC/majac/jswriter.vala"
			_tmp19_ = self->priv->temp_filename;
#line 131 "/home/digi/Documents/MajaC/majac/jswriter.vala"
			g_unlink (_tmp19_);
#line 482 "jswriter.c"
		}
	}
}


/**
 * Writes tabs according to the current indent level.
 */
void maja_js_writer_write_indent (MajaJSWriter* self) {
	gboolean _tmp0_;
	gboolean _tmp1_;
#line 139 "/home/digi/Documents/MajaC/majac/jswriter.vala"
	g_return_if_fail (self != NULL);
#line 140 "/home/digi/Documents/MajaC/majac/jswriter.vala"
	_tmp0_ = maja_js_writer_get_bol (self);
#line 140 "/home/digi/Documents/MajaC/majac/jswriter.vala"
	_tmp1_ = _tmp0_;
#line 140 "/home/digi/Documents/MajaC/majac/jswriter.vala"
	if (!_tmp1_) {
#line 141 "/home/digi/Documents/MajaC/majac/jswriter.vala"
		maja_js_writer_write_newline (self);
#line 504 "jswriter.c"
	}
	{
		gint i;
#line 144 "/home/digi/Documents/MajaC/majac/jswriter.vala"
		i = 0;
#line 510 "jswriter.c"
		{
			gboolean _tmp2_;
#line 144 "/home/digi/Documents/MajaC/majac/jswriter.vala"
			_tmp2_ = TRUE;
#line 144 "/home/digi/Documents/MajaC/majac/jswriter.vala"
			while (TRUE) {
#line 517 "jswriter.c"
				gboolean _tmp3_;
				gint _tmp5_;
				gint _tmp6_;
				FILE* _tmp7_;
#line 144 "/home/digi/Documents/MajaC/majac/jswriter.vala"
				_tmp3_ = _tmp2_;
#line 144 "/home/digi/Documents/MajaC/majac/jswriter.vala"
				if (!_tmp3_) {
#line 526 "jswriter.c"
					gint _tmp4_;
#line 144 "/home/digi/Documents/MajaC/majac/jswriter.vala"
					_tmp4_ = i;
#line 144 "/home/digi/Documents/MajaC/majac/jswriter.vala"
					i = _tmp4_ + 1;
#line 532 "jswriter.c"
				}
#line 144 "/home/digi/Documents/MajaC/majac/jswriter.vala"
				_tmp2_ = FALSE;
#line 144 "/home/digi/Documents/MajaC/majac/jswriter.vala"
				_tmp5_ = i;
#line 144 "/home/digi/Documents/MajaC/majac/jswriter.vala"
				_tmp6_ = self->priv->indent;
#line 144 "/home/digi/Documents/MajaC/majac/jswriter.vala"
				if (!(_tmp5_ < _tmp6_)) {
#line 144 "/home/digi/Documents/MajaC/majac/jswriter.vala"
					break;
#line 544 "jswriter.c"
				}
#line 145 "/home/digi/Documents/MajaC/majac/jswriter.vala"
				_tmp7_ = self->priv->stream;
#line 145 "/home/digi/Documents/MajaC/majac/jswriter.vala"
				fputc ('\t', _tmp7_);
#line 550 "jswriter.c"
			}
		}
	}
#line 148 "/home/digi/Documents/MajaC/majac/jswriter.vala"
	self->priv->_bol = FALSE;
#line 556 "jswriter.c"
}


/**
 * Writes the specified string.
 *
 * @param s a string
 */
void maja_js_writer_write_string (MajaJSWriter* self, const gchar* s) {
	FILE* _tmp0_;
	const gchar* _tmp1_;
#line 156 "/home/digi/Documents/MajaC/majac/jswriter.vala"
	g_return_if_fail (self != NULL);
#line 156 "/home/digi/Documents/MajaC/majac/jswriter.vala"
	g_return_if_fail (s != NULL);
#line 157 "/home/digi/Documents/MajaC/majac/jswriter.vala"
	_tmp0_ = self->priv->stream;
#line 157 "/home/digi/Documents/MajaC/majac/jswriter.vala"
	_tmp1_ = s;
#line 157 "/home/digi/Documents/MajaC/majac/jswriter.vala"
	fputs (_tmp1_, _tmp0_);
#line 158 "/home/digi/Documents/MajaC/majac/jswriter.vala"
	self->priv->_bol = FALSE;
#line 580 "jswriter.c"
}


/**
 * Writes a newline.
 */
void maja_js_writer_write_newline (MajaJSWriter* self) {
	FILE* _tmp0_;
#line 164 "/home/digi/Documents/MajaC/majac/jswriter.vala"
	g_return_if_fail (self != NULL);
#line 165 "/home/digi/Documents/MajaC/majac/jswriter.vala"
	_tmp0_ = self->priv->stream;
#line 165 "/home/digi/Documents/MajaC/majac/jswriter.vala"
	fputc ('\n', _tmp0_);
#line 166 "/home/digi/Documents/MajaC/majac/jswriter.vala"
	self->priv->_bol = TRUE;
#line 597 "jswriter.c"
}


/**
 * Opens a new block, increasing the indent level.
 */
void maja_js_writer_write_begin_block (MajaJSWriter* self) {
	gboolean _tmp0_;
	gboolean _tmp1_;
	FILE* _tmp3_;
	gint _tmp4_;
#line 172 "/home/digi/Documents/MajaC/majac/jswriter.vala"
	g_return_if_fail (self != NULL);
#line 173 "/home/digi/Documents/MajaC/majac/jswriter.vala"
	_tmp0_ = maja_js_writer_get_bol (self);
#line 173 "/home/digi/Documents/MajaC/majac/jswriter.vala"
	_tmp1_ = _tmp0_;
#line 173 "/home/digi/Documents/MajaC/majac/jswriter.vala"
	if (!_tmp1_) {
#line 617 "jswriter.c"
		FILE* _tmp2_;
#line 174 "/home/digi/Documents/MajaC/majac/jswriter.vala"
		_tmp2_ = self->priv->stream;
#line 174 "/home/digi/Documents/MajaC/majac/jswriter.vala"
		fputc (' ', _tmp2_);
#line 623 "jswriter.c"
	} else {
#line 176 "/home/digi/Documents/MajaC/majac/jswriter.vala"
		maja_js_writer_write_indent (self);
#line 627 "jswriter.c"
	}
#line 178 "/home/digi/Documents/MajaC/majac/jswriter.vala"
	_tmp3_ = self->priv->stream;
#line 178 "/home/digi/Documents/MajaC/majac/jswriter.vala"
	fputc ('{', _tmp3_);
#line 179 "/home/digi/Documents/MajaC/majac/jswriter.vala"
	maja_js_writer_write_newline (self);
#line 180 "/home/digi/Documents/MajaC/majac/jswriter.vala"
	_tmp4_ = self->priv->indent;
#line 180 "/home/digi/Documents/MajaC/majac/jswriter.vala"
	self->priv->indent = _tmp4_ + 1;
#line 639 "jswriter.c"
}


/**
 * Closes the current block, decreasing the indent level.
 */
void maja_js_writer_write_end_block (MajaJSWriter* self) {
	gint _tmp0_;
	gint _tmp1_;
	FILE* _tmp2_;
#line 186 "/home/digi/Documents/MajaC/majac/jswriter.vala"
	g_return_if_fail (self != NULL);
#line 187 "/home/digi/Documents/MajaC/majac/jswriter.vala"
	_tmp0_ = self->priv->indent;
#line 187 "/home/digi/Documents/MajaC/majac/jswriter.vala"
	g_assert (_tmp0_ > 0);
#line 189 "/home/digi/Documents/MajaC/majac/jswriter.vala"
	_tmp1_ = self->priv->indent;
#line 189 "/home/digi/Documents/MajaC/majac/jswriter.vala"
	self->priv->indent = _tmp1_ - 1;
#line 190 "/home/digi/Documents/MajaC/majac/jswriter.vala"
	maja_js_writer_write_indent (self);
#line 191 "/home/digi/Documents/MajaC/majac/jswriter.vala"
	_tmp2_ = self->priv->stream;
#line 191 "/home/digi/Documents/MajaC/majac/jswriter.vala"
	fputc ('}', _tmp2_);
#line 666 "jswriter.c"
}


/**
 * Writes the specified text as comment.
 *
 * @param text the comment text
 */
void maja_js_writer_write_comment (MajaJSWriter* self, const gchar* text) {
	GError * _inner_error_ = NULL;
#line 199 "/home/digi/Documents/MajaC/majac/jswriter.vala"
	g_return_if_fail (self != NULL);
#line 199 "/home/digi/Documents/MajaC/majac/jswriter.vala"
	g_return_if_fail (text != NULL);
#line 681 "jswriter.c"
	{
		FILE* _tmp0_;
		gboolean first;
		GRegex* _tmp1_;
		GRegex* regex;
		const gchar* _tmp2_;
		gchar** _tmp3_;
		gchar** _tmp4_ = NULL;
		gchar** lines;
		gint lines_length1;
		gint _lines_size_;
		gchar** _tmp5_;
		gint _tmp5__length1;
		FILE* _tmp30_;
#line 201 "/home/digi/Documents/MajaC/majac/jswriter.vala"
		maja_js_writer_write_indent (self);
#line 202 "/home/digi/Documents/MajaC/majac/jswriter.vala"
		_tmp0_ = self->priv->stream;
#line 202 "/home/digi/Documents/MajaC/majac/jswriter.vala"
		fputs ("/*", _tmp0_);
#line 203 "/home/digi/Documents/MajaC/majac/jswriter.vala"
		first = TRUE;
#line 206 "/home/digi/Documents/MajaC/majac/jswriter.vala"
		_tmp1_ = g_regex_new ("^\t+", 0, 0, &_inner_error_);
#line 206 "/home/digi/Documents/MajaC/majac/jswriter.vala"
		regex = _tmp1_;
#line 206 "/home/digi/Documents/MajaC/majac/jswriter.vala"
		if (_inner_error_ != NULL) {
#line 206 "/home/digi/Documents/MajaC/majac/jswriter.vala"
			if (_inner_error_->domain == G_REGEX_ERROR) {
#line 712 "jswriter.c"
				goto __catch3_g_regex_error;
			}
#line 206 "/home/digi/Documents/MajaC/majac/jswriter.vala"
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 206 "/home/digi/Documents/MajaC/majac/jswriter.vala"
			g_clear_error (&_inner_error_);
#line 206 "/home/digi/Documents/MajaC/majac/jswriter.vala"
			return;
#line 721 "jswriter.c"
		}
#line 209 "/home/digi/Documents/MajaC/majac/jswriter.vala"
		_tmp2_ = text;
#line 209 "/home/digi/Documents/MajaC/majac/jswriter.vala"
		_tmp4_ = _tmp3_ = g_strsplit (_tmp2_, "\n", 0);
#line 209 "/home/digi/Documents/MajaC/majac/jswriter.vala"
		lines = _tmp4_;
#line 209 "/home/digi/Documents/MajaC/majac/jswriter.vala"
		lines_length1 = _vala_array_length (_tmp3_);
#line 209 "/home/digi/Documents/MajaC/majac/jswriter.vala"
		_lines_size_ = lines_length1;
#line 211 "/home/digi/Documents/MajaC/majac/jswriter.vala"
		_tmp5_ = lines;
#line 211 "/home/digi/Documents/MajaC/majac/jswriter.vala"
		_tmp5__length1 = lines_length1;
#line 737 "jswriter.c"
		{
			gchar** line_collection = NULL;
			gint line_collection_length1 = 0;
			gint _line_collection_size_ = 0;
			gint line_it = 0;
#line 211 "/home/digi/Documents/MajaC/majac/jswriter.vala"
			line_collection = _tmp5_;
#line 211 "/home/digi/Documents/MajaC/majac/jswriter.vala"
			line_collection_length1 = _tmp5__length1;
#line 211 "/home/digi/Documents/MajaC/majac/jswriter.vala"
			for (line_it = 0; line_it < _tmp5__length1; line_it = line_it + 1) {
#line 749 "jswriter.c"
				gchar* _tmp6_;
				gchar* line = NULL;
#line 211 "/home/digi/Documents/MajaC/majac/jswriter.vala"
				_tmp6_ = g_strdup (line_collection[line_it]);
#line 211 "/home/digi/Documents/MajaC/majac/jswriter.vala"
				line = _tmp6_;
#line 756 "jswriter.c"
				{
					gboolean _tmp7_;
					GRegex* _tmp8_;
					const gchar* _tmp9_;
					gchar* _tmp10_ = NULL;
					gchar* _tmp11_;
					gchar* _tmp12_;
					gchar** _tmp13_;
					gchar** _tmp14_ = NULL;
					gchar** _tmp15_;
					gint _tmp15__length1;
					gchar** lineparts;
					gint lineparts_length1;
					gint _lineparts_size_;
#line 212 "/home/digi/Documents/MajaC/majac/jswriter.vala"
					_tmp7_ = first;
#line 212 "/home/digi/Documents/MajaC/majac/jswriter.vala"
					if (!_tmp7_) {
#line 213 "/home/digi/Documents/MajaC/majac/jswriter.vala"
						maja_js_writer_write_indent (self);
#line 777 "jswriter.c"
					} else {
#line 215 "/home/digi/Documents/MajaC/majac/jswriter.vala"
						first = FALSE;
#line 781 "jswriter.c"
					}
#line 218 "/home/digi/Documents/MajaC/majac/jswriter.vala"
					_tmp8_ = regex;
#line 218 "/home/digi/Documents/MajaC/majac/jswriter.vala"
					_tmp9_ = line;
#line 218 "/home/digi/Documents/MajaC/majac/jswriter.vala"
					_tmp10_ = g_regex_replace_literal (_tmp8_, _tmp9_, (gssize) (-1), 0, "", 0, &_inner_error_);
#line 218 "/home/digi/Documents/MajaC/majac/jswriter.vala"
					_tmp11_ = _tmp10_;
#line 218 "/home/digi/Documents/MajaC/majac/jswriter.vala"
					if (_inner_error_ != NULL) {
#line 218 "/home/digi/Documents/MajaC/majac/jswriter.vala"
						_g_free0 (line);
#line 218 "/home/digi/Documents/MajaC/majac/jswriter.vala"
						lines = (_vala_array_free (lines, lines_length1, (GDestroyNotify) g_free), NULL);
#line 218 "/home/digi/Documents/MajaC/majac/jswriter.vala"
						_g_regex_unref0 (regex);
#line 218 "/home/digi/Documents/MajaC/majac/jswriter.vala"
						if (_inner_error_->domain == G_REGEX_ERROR) {
#line 801 "jswriter.c"
							goto __catch3_g_regex_error;
						}
#line 218 "/home/digi/Documents/MajaC/majac/jswriter.vala"
						_g_free0 (line);
#line 218 "/home/digi/Documents/MajaC/majac/jswriter.vala"
						lines = (_vala_array_free (lines, lines_length1, (GDestroyNotify) g_free), NULL);
#line 218 "/home/digi/Documents/MajaC/majac/jswriter.vala"
						_g_regex_unref0 (regex);
#line 218 "/home/digi/Documents/MajaC/majac/jswriter.vala"
						g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 218 "/home/digi/Documents/MajaC/majac/jswriter.vala"
						g_clear_error (&_inner_error_);
#line 218 "/home/digi/Documents/MajaC/majac/jswriter.vala"
						return;
#line 816 "jswriter.c"
					}
#line 218 "/home/digi/Documents/MajaC/majac/jswriter.vala"
					_tmp12_ = _tmp11_;
#line 218 "/home/digi/Documents/MajaC/majac/jswriter.vala"
					_tmp14_ = _tmp13_ = g_strsplit (_tmp12_, "*/", 0);
#line 218 "/home/digi/Documents/MajaC/majac/jswriter.vala"
					_tmp15_ = _tmp14_;
#line 218 "/home/digi/Documents/MajaC/majac/jswriter.vala"
					_tmp15__length1 = _vala_array_length (_tmp13_);
#line 218 "/home/digi/Documents/MajaC/majac/jswriter.vala"
					_g_free0 (_tmp12_);
#line 218 "/home/digi/Documents/MajaC/majac/jswriter.vala"
					lineparts = _tmp15_;
#line 218 "/home/digi/Documents/MajaC/majac/jswriter.vala"
					lineparts_length1 = _tmp15__length1;
#line 218 "/home/digi/Documents/MajaC/majac/jswriter.vala"
					_lineparts_size_ = lineparts_length1;
#line 834 "jswriter.c"
					{
						gint i;
#line 220 "/home/digi/Documents/MajaC/majac/jswriter.vala"
						i = 0;
#line 839 "jswriter.c"
						{
							gboolean _tmp16_;
#line 220 "/home/digi/Documents/MajaC/majac/jswriter.vala"
							_tmp16_ = TRUE;
#line 220 "/home/digi/Documents/MajaC/majac/jswriter.vala"
							while (TRUE) {
#line 846 "jswriter.c"
								gboolean _tmp17_;
								gchar** _tmp19_;
								gint _tmp19__length1;
								gint _tmp20_;
								const gchar* _tmp21_;
								FILE* _tmp22_;
								gchar** _tmp23_;
								gint _tmp23__length1;
								gint _tmp24_;
								const gchar* _tmp25_;
								gchar** _tmp26_;
								gint _tmp26__length1;
								gint _tmp27_;
								const gchar* _tmp28_;
#line 220 "/home/digi/Documents/MajaC/majac/jswriter.vala"
								_tmp17_ = _tmp16_;
#line 220 "/home/digi/Documents/MajaC/majac/jswriter.vala"
								if (!_tmp17_) {
#line 865 "jswriter.c"
									gint _tmp18_;
#line 220 "/home/digi/Documents/MajaC/majac/jswriter.vala"
									_tmp18_ = i;
#line 220 "/home/digi/Documents/MajaC/majac/jswriter.vala"
									i = _tmp18_ + 1;
#line 871 "jswriter.c"
								}
#line 220 "/home/digi/Documents/MajaC/majac/jswriter.vala"
								_tmp16_ = FALSE;
#line 220 "/home/digi/Documents/MajaC/majac/jswriter.vala"
								_tmp19_ = lineparts;
#line 220 "/home/digi/Documents/MajaC/majac/jswriter.vala"
								_tmp19__length1 = lineparts_length1;
#line 220 "/home/digi/Documents/MajaC/majac/jswriter.vala"
								_tmp20_ = i;
#line 220 "/home/digi/Documents/MajaC/majac/jswriter.vala"
								_tmp21_ = _tmp19_[_tmp20_];
#line 220 "/home/digi/Documents/MajaC/majac/jswriter.vala"
								if (!(_tmp21_ != NULL)) {
#line 220 "/home/digi/Documents/MajaC/majac/jswriter.vala"
									break;
#line 887 "jswriter.c"
								}
#line 221 "/home/digi/Documents/MajaC/majac/jswriter.vala"
								_tmp22_ = self->priv->stream;
#line 221 "/home/digi/Documents/MajaC/majac/jswriter.vala"
								_tmp23_ = lineparts;
#line 221 "/home/digi/Documents/MajaC/majac/jswriter.vala"
								_tmp23__length1 = lineparts_length1;
#line 221 "/home/digi/Documents/MajaC/majac/jswriter.vala"
								_tmp24_ = i;
#line 221 "/home/digi/Documents/MajaC/majac/jswriter.vala"
								_tmp25_ = _tmp23_[_tmp24_];
#line 221 "/home/digi/Documents/MajaC/majac/jswriter.vala"
								fputs (_tmp25_, _tmp22_);
#line 222 "/home/digi/Documents/MajaC/majac/jswriter.vala"
								_tmp26_ = lineparts;
#line 222 "/home/digi/Documents/MajaC/majac/jswriter.vala"
								_tmp26__length1 = lineparts_length1;
#line 222 "/home/digi/Documents/MajaC/majac/jswriter.vala"
								_tmp27_ = i;
#line 222 "/home/digi/Documents/MajaC/majac/jswriter.vala"
								_tmp28_ = _tmp26_[_tmp27_ + 1];
#line 222 "/home/digi/Documents/MajaC/majac/jswriter.vala"
								if (_tmp28_ != NULL) {
#line 911 "jswriter.c"
									FILE* _tmp29_;
#line 223 "/home/digi/Documents/MajaC/majac/jswriter.vala"
									_tmp29_ = self->priv->stream;
#line 223 "/home/digi/Documents/MajaC/majac/jswriter.vala"
									fputs ("* /", _tmp29_);
#line 917 "jswriter.c"
								}
							}
						}
					}
#line 211 "/home/digi/Documents/MajaC/majac/jswriter.vala"
					lineparts = (_vala_array_free (lineparts, lineparts_length1, (GDestroyNotify) g_free), NULL);
#line 211 "/home/digi/Documents/MajaC/majac/jswriter.vala"
					_g_free0 (line);
#line 926 "jswriter.c"
				}
			}
		}
#line 227 "/home/digi/Documents/MajaC/majac/jswriter.vala"
		_tmp30_ = self->priv->stream;
#line 227 "/home/digi/Documents/MajaC/majac/jswriter.vala"
		fputs ("*/", _tmp30_);
#line 228 "/home/digi/Documents/MajaC/majac/jswriter.vala"
		maja_js_writer_write_newline (self);
#line 200 "/home/digi/Documents/MajaC/majac/jswriter.vala"
		lines = (_vala_array_free (lines, lines_length1, (GDestroyNotify) g_free), NULL);
#line 200 "/home/digi/Documents/MajaC/majac/jswriter.vala"
		_g_regex_unref0 (regex);
#line 940 "jswriter.c"
	}
	goto __finally3;
	__catch3_g_regex_error:
	{
		GError* e = NULL;
#line 200 "/home/digi/Documents/MajaC/majac/jswriter.vala"
		e = _inner_error_;
#line 200 "/home/digi/Documents/MajaC/majac/jswriter.vala"
		_inner_error_ = NULL;
#line 200 "/home/digi/Documents/MajaC/majac/jswriter.vala"
		_g_error_free0 (e);
#line 952 "jswriter.c"
	}
	__finally3:
#line 200 "/home/digi/Documents/MajaC/majac/jswriter.vala"
	if (_inner_error_ != NULL) {
#line 200 "/home/digi/Documents/MajaC/majac/jswriter.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 200 "/home/digi/Documents/MajaC/majac/jswriter.vala"
		g_clear_error (&_inner_error_);
#line 200 "/home/digi/Documents/MajaC/majac/jswriter.vala"
		return;
#line 963 "jswriter.c"
	}
}


const gchar* maja_js_writer_get_filename (MajaJSWriter* self) {
	const gchar* result;
	const gchar* _tmp0_;
#line 34 "/home/digi/Documents/MajaC/majac/jswriter.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 34 "/home/digi/Documents/MajaC/majac/jswriter.vala"
	_tmp0_ = self->priv->_filename;
#line 34 "/home/digi/Documents/MajaC/majac/jswriter.vala"
	result = _tmp0_;
#line 34 "/home/digi/Documents/MajaC/majac/jswriter.vala"
	return result;
#line 979 "jswriter.c"
}


void maja_js_writer_set_filename (MajaJSWriter* self, const gchar* value) {
	const gchar* _tmp0_;
	gchar* _tmp1_;
#line 34 "/home/digi/Documents/MajaC/majac/jswriter.vala"
	g_return_if_fail (self != NULL);
#line 34 "/home/digi/Documents/MajaC/majac/jswriter.vala"
	_tmp0_ = value;
#line 34 "/home/digi/Documents/MajaC/majac/jswriter.vala"
	_tmp1_ = g_strdup (_tmp0_);
#line 34 "/home/digi/Documents/MajaC/majac/jswriter.vala"
	_g_free0 (self->priv->_filename);
#line 34 "/home/digi/Documents/MajaC/majac/jswriter.vala"
	self->priv->_filename = _tmp1_;
#line 996 "jswriter.c"
}


gboolean maja_js_writer_get_bol (MajaJSWriter* self) {
	gboolean result;
	gboolean _tmp0_;
#line 45 "/home/digi/Documents/MajaC/majac/jswriter.vala"
	g_return_val_if_fail (self != NULL, FALSE);
#line 45 "/home/digi/Documents/MajaC/majac/jswriter.vala"
	_tmp0_ = self->priv->_bol;
#line 45 "/home/digi/Documents/MajaC/majac/jswriter.vala"
	result = _tmp0_;
#line 45 "/home/digi/Documents/MajaC/majac/jswriter.vala"
	return result;
#line 1011 "jswriter.c"
}


static void maja_value_js_writer_init (GValue* value) {
#line 30 "/home/digi/Documents/MajaC/majac/jswriter.vala"
	value->data[0].v_pointer = NULL;
#line 1018 "jswriter.c"
}


static void maja_value_js_writer_free_value (GValue* value) {
#line 30 "/home/digi/Documents/MajaC/majac/jswriter.vala"
	if (value->data[0].v_pointer) {
#line 30 "/home/digi/Documents/MajaC/majac/jswriter.vala"
		maja_js_writer_unref (value->data[0].v_pointer);
#line 1027 "jswriter.c"
	}
}


static void maja_value_js_writer_copy_value (const GValue* src_value, GValue* dest_value) {
#line 30 "/home/digi/Documents/MajaC/majac/jswriter.vala"
	if (src_value->data[0].v_pointer) {
#line 30 "/home/digi/Documents/MajaC/majac/jswriter.vala"
		dest_value->data[0].v_pointer = maja_js_writer_ref (src_value->data[0].v_pointer);
#line 1037 "jswriter.c"
	} else {
#line 30 "/home/digi/Documents/MajaC/majac/jswriter.vala"
		dest_value->data[0].v_pointer = NULL;
#line 1041 "jswriter.c"
	}
}


static gpointer maja_value_js_writer_peek_pointer (const GValue* value) {
#line 30 "/home/digi/Documents/MajaC/majac/jswriter.vala"
	return value->data[0].v_pointer;
#line 1049 "jswriter.c"
}


static gchar* maja_value_js_writer_collect_value (GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
#line 30 "/home/digi/Documents/MajaC/majac/jswriter.vala"
	if (collect_values[0].v_pointer) {
#line 1056 "jswriter.c"
		MajaJSWriter* object;
		object = collect_values[0].v_pointer;
#line 30 "/home/digi/Documents/MajaC/majac/jswriter.vala"
		if (object->parent_instance.g_class == NULL) {
#line 30 "/home/digi/Documents/MajaC/majac/jswriter.vala"
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
#line 1063 "jswriter.c"
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
#line 30 "/home/digi/Documents/MajaC/majac/jswriter.vala"
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
#line 1067 "jswriter.c"
		}
#line 30 "/home/digi/Documents/MajaC/majac/jswriter.vala"
		value->data[0].v_pointer = maja_js_writer_ref (object);
#line 1071 "jswriter.c"
	} else {
#line 30 "/home/digi/Documents/MajaC/majac/jswriter.vala"
		value->data[0].v_pointer = NULL;
#line 1075 "jswriter.c"
	}
#line 30 "/home/digi/Documents/MajaC/majac/jswriter.vala"
	return NULL;
#line 1079 "jswriter.c"
}


static gchar* maja_value_js_writer_lcopy_value (const GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	MajaJSWriter** object_p;
	object_p = collect_values[0].v_pointer;
#line 30 "/home/digi/Documents/MajaC/majac/jswriter.vala"
	if (!object_p) {
#line 30 "/home/digi/Documents/MajaC/majac/jswriter.vala"
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
#line 1090 "jswriter.c"
	}
#line 30 "/home/digi/Documents/MajaC/majac/jswriter.vala"
	if (!value->data[0].v_pointer) {
#line 30 "/home/digi/Documents/MajaC/majac/jswriter.vala"
		*object_p = NULL;
#line 1096 "jswriter.c"
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
#line 30 "/home/digi/Documents/MajaC/majac/jswriter.vala"
		*object_p = value->data[0].v_pointer;
#line 1100 "jswriter.c"
	} else {
#line 30 "/home/digi/Documents/MajaC/majac/jswriter.vala"
		*object_p = maja_js_writer_ref (value->data[0].v_pointer);
#line 1104 "jswriter.c"
	}
#line 30 "/home/digi/Documents/MajaC/majac/jswriter.vala"
	return NULL;
#line 1108 "jswriter.c"
}


GParamSpec* maja_param_spec_js_writer (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags) {
	MajaParamSpecJSWriter* spec;
#line 30 "/home/digi/Documents/MajaC/majac/jswriter.vala"
	g_return_val_if_fail (g_type_is_a (object_type, MAJA_TYPE_JS_WRITER), NULL);
#line 30 "/home/digi/Documents/MajaC/majac/jswriter.vala"
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
#line 30 "/home/digi/Documents/MajaC/majac/jswriter.vala"
	G_PARAM_SPEC (spec)->value_type = object_type;
#line 30 "/home/digi/Documents/MajaC/majac/jswriter.vala"
	return G_PARAM_SPEC (spec);
#line 1122 "jswriter.c"
}


gpointer maja_value_get_js_writer (const GValue* value) {
#line 30 "/home/digi/Documents/MajaC/majac/jswriter.vala"
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, MAJA_TYPE_JS_WRITER), NULL);
#line 30 "/home/digi/Documents/MajaC/majac/jswriter.vala"
	return value->data[0].v_pointer;
#line 1131 "jswriter.c"
}


void maja_value_set_js_writer (GValue* value, gpointer v_object) {
	MajaJSWriter* old;
#line 30 "/home/digi/Documents/MajaC/majac/jswriter.vala"
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, MAJA_TYPE_JS_WRITER));
#line 30 "/home/digi/Documents/MajaC/majac/jswriter.vala"
	old = value->data[0].v_pointer;
#line 30 "/home/digi/Documents/MajaC/majac/jswriter.vala"
	if (v_object) {
#line 30 "/home/digi/Documents/MajaC/majac/jswriter.vala"
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, MAJA_TYPE_JS_WRITER));
#line 30 "/home/digi/Documents/MajaC/majac/jswriter.vala"
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
#line 30 "/home/digi/Documents/MajaC/majac/jswriter.vala"
		value->data[0].v_pointer = v_object;
#line 30 "/home/digi/Documents/MajaC/majac/jswriter.vala"
		maja_js_writer_ref (value->data[0].v_pointer);
#line 1151 "jswriter.c"
	} else {
#line 30 "/home/digi/Documents/MajaC/majac/jswriter.vala"
		value->data[0].v_pointer = NULL;
#line 1155 "jswriter.c"
	}
#line 30 "/home/digi/Documents/MajaC/majac/jswriter.vala"
	if (old) {
#line 30 "/home/digi/Documents/MajaC/majac/jswriter.vala"
		maja_js_writer_unref (old);
#line 1161 "jswriter.c"
	}
}


void maja_value_take_js_writer (GValue* value, gpointer v_object) {
	MajaJSWriter* old;
#line 30 "/home/digi/Documents/MajaC/majac/jswriter.vala"
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, MAJA_TYPE_JS_WRITER));
#line 30 "/home/digi/Documents/MajaC/majac/jswriter.vala"
	old = value->data[0].v_pointer;
#line 30 "/home/digi/Documents/MajaC/majac/jswriter.vala"
	if (v_object) {
#line 30 "/home/digi/Documents/MajaC/majac/jswriter.vala"
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, MAJA_TYPE_JS_WRITER));
#line 30 "/home/digi/Documents/MajaC/majac/jswriter.vala"
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
#line 30 "/home/digi/Documents/MajaC/majac/jswriter.vala"
		value->data[0].v_pointer = v_object;
#line 1180 "jswriter.c"
	} else {
#line 30 "/home/digi/Documents/MajaC/majac/jswriter.vala"
		value->data[0].v_pointer = NULL;
#line 1184 "jswriter.c"
	}
#line 30 "/home/digi/Documents/MajaC/majac/jswriter.vala"
	if (old) {
#line 30 "/home/digi/Documents/MajaC/majac/jswriter.vala"
		maja_js_writer_unref (old);
#line 1190 "jswriter.c"
	}
}


static void maja_js_writer_class_init (MajaJSWriterClass * klass) {
#line 30 "/home/digi/Documents/MajaC/majac/jswriter.vala"
	maja_js_writer_parent_class = g_type_class_peek_parent (klass);
#line 30 "/home/digi/Documents/MajaC/majac/jswriter.vala"
	MAJA_JS_WRITER_CLASS (klass)->finalize = maja_js_writer_finalize;
#line 30 "/home/digi/Documents/MajaC/majac/jswriter.vala"
	g_type_class_add_private (klass, sizeof (MajaJSWriterPrivate));
#line 1202 "jswriter.c"
}


static void maja_js_writer_instance_init (MajaJSWriter * self) {
#line 30 "/home/digi/Documents/MajaC/majac/jswriter.vala"
	self->priv = MAJA_JS_WRITER_GET_PRIVATE (self);
#line 56 "/home/digi/Documents/MajaC/majac/jswriter.vala"
	self->priv->_bol = TRUE;
#line 30 "/home/digi/Documents/MajaC/majac/jswriter.vala"
	self->ref_count = 1;
#line 1213 "jswriter.c"
}


static void maja_js_writer_finalize (MajaJSWriter* obj) {
	MajaJSWriter * self;
#line 30 "/home/digi/Documents/MajaC/majac/jswriter.vala"
	self = MAJA_JS_WRITER (obj);
#line 34 "/home/digi/Documents/MajaC/majac/jswriter.vala"
	_g_free0 (self->priv->_filename);
#line 39 "/home/digi/Documents/MajaC/majac/jswriter.vala"
	_g_free0 (self->priv->source_filename);
#line 48 "/home/digi/Documents/MajaC/majac/jswriter.vala"
	_g_free0 (self->priv->temp_filename);
#line 51 "/home/digi/Documents/MajaC/majac/jswriter.vala"
	_fclose0 (self->priv->stream);
#line 1229 "jswriter.c"
}


/**
 * Represents a writer to write JavaScript source files.
 */
GType maja_js_writer_get_type (void) {
	static volatile gsize maja_js_writer_type_id__volatile = 0;
	if (g_once_init_enter (&maja_js_writer_type_id__volatile)) {
		static const GTypeValueTable g_define_type_value_table = { maja_value_js_writer_init, maja_value_js_writer_free_value, maja_value_js_writer_copy_value, maja_value_js_writer_peek_pointer, "p", maja_value_js_writer_collect_value, "p", maja_value_js_writer_lcopy_value };
		static const GTypeInfo g_define_type_info = { sizeof (MajaJSWriterClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) maja_js_writer_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (MajaJSWriter), 0, (GInstanceInitFunc) maja_js_writer_instance_init, &g_define_type_value_table };
		static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
		GType maja_js_writer_type_id;
		maja_js_writer_type_id = g_type_register_fundamental (g_type_fundamental_next (), "MajaJSWriter", &g_define_type_info, &g_define_type_fundamental_info, 0);
		g_once_init_leave (&maja_js_writer_type_id__volatile, maja_js_writer_type_id);
	}
	return maja_js_writer_type_id__volatile;
}


gpointer maja_js_writer_ref (gpointer instance) {
	MajaJSWriter* self;
	self = instance;
#line 30 "/home/digi/Documents/MajaC/majac/jswriter.vala"
	g_atomic_int_inc (&self->ref_count);
#line 30 "/home/digi/Documents/MajaC/majac/jswriter.vala"
	return instance;
#line 1257 "jswriter.c"
}


void maja_js_writer_unref (gpointer instance) {
	MajaJSWriter* self;
	self = instance;
#line 30 "/home/digi/Documents/MajaC/majac/jswriter.vala"
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
#line 30 "/home/digi/Documents/MajaC/majac/jswriter.vala"
		MAJA_JS_WRITER_GET_CLASS (self)->finalize (self);
#line 30 "/home/digi/Documents/MajaC/majac/jswriter.vala"
		g_type_free_instance ((GTypeInstance *) self);
#line 1270 "jswriter.c"
	}
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}


static gint _vala_array_length (gpointer array) {
	int length;
	length = 0;
	if (array) {
		while (((gpointer*) array)[length]) {
			length++;
		}
	}
	return length;
}



